### ISSUE TITLE
[Epic] 요청작 상세 페이지 구현하기

### ISSUE THREAD

**Issue by sunghyuki** [Collusic/collusic-new#12]
* [ ] 기여작 리스트 조회 API 구현하기
* [ ] 기여작 채택 기능 구현하기
* [ ] 음원 재생 구현하기
* [ ] 기여작 리스트 조회 테스트 코드 작성하기
* [ ] 기여자 채택 기능 테스트 코드 작성하기
